---
permalink: sg120-1200/replacing-fan-in-sg120-and-sg1200.html 
sidebar: sidebar 
keywords: storagegrid, sg120, sg1200, admin appliance, replacing, replace, fan, remove, removing, removal, install, installing 
summary: 'Gli apparecchi SG120 o SG1200 sono dotati di otto ventole di raffreddamento. Se una delle ventole si guasta, è necessario sostituirla il prima possibile per garantire un raffreddamento adeguato dell"apparecchio.' 
---
= Sostituire la ventola in un SG120 o SG1200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gli apparecchi SG120 o SG1200 sono dotati di sette ventole di raffreddamento. Se una delle ventole si guasta, è necessario sostituirla il prima possibile per garantire che l'apparecchio abbia un raffreddamento adeguato.

.A proposito di questa attività
Per evitare interruzioni del servizio, verificare che tutti gli altri nodi storage siano collegati alla griglia prima di iniziare la sostituzione della ventola o sostituire la ventola durante una finestra di manutenzione programmata in caso di accettabili periodi di interruzione del servizio. Vedere le informazioni su https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states["monitoraggio degli stati di connessione del nodo"^].

Il nodo dell'appliance non sarà accessibile durante la sostituzione della ventola.

Le ventole di raffreddamento sono accessibili dopo aver rimosso il coperchio superiore dell'apparecchio.


NOTE: Ciascuna delle due unità di alimentazione contiene anche una ventola. Le ventole dell'alimentatore non sono incluse in questa procedura.

.Prima di iniziare
* Si dispone della ventola sostitutiva corretta.
* Lo hai fatto link:verify-component-to-replace.html["determinata la posizione della ventola da sostituire"].
* Ti trovi link:locating-sg120-and-sg1200-in-data-center.html["posizionare fisicamente l'appliance SG120 o SG1200"] nella situazione in cui devi sostituire la ventola nel data center.
+

NOTE: A link:power-sg120-and-sg1200-off-on.html#shut-down-the-sg120-or-sg1200-appliance["spegnimento controllato dell'apparecchio"] è necessario prima di rimuovere l'apparecchio dal rack.

* Hai scollegato tutti i cavi e link:reinstalling-sg120-and-sg1200-cover.html["rimuovere il coperchio dell'apparecchio"].
* Hai confermato che le altre ventole sono installate e in esecuzione.


.Fasi
. Avvolgere l'estremità del braccialetto ESD intorno al polso e fissare l'estremità del fermaglio a una messa a terra metallica per evitare scariche elettrostatiche.
. Individuare la ventola da sostituire.
+
Le sette ventole sono nelle seguenti posizioni nello chassis (metà anteriore dell'appliance StorageGRID con il coperchio superiore rimosso mostrata):

+
image::../media/drw_fan_position_ieops-2614.svg[Posizioni delle ventole nello chassis StorageGRID]

+
|===
| Posizione del chassis | Gruppo ventola 


 a| 
1
 a| 
Fan_SYS0



 a| 
2
 a| 
Fan_SYS1



 a| 
3
 a| 
Fan_SYS2



 a| 
4
 a| 
Fan_SYS3



 a| 
5
 a| 
Fan_SYS4



 a| 
6
 a| 
Fan_SYS5



 a| 
7
 a| 
Fan_SYS6

|===
. Utilizzando le linguette blu sulla ventola, estrarre la ventola guasta dal telaio.
+
image:../media/drw_s2025_fan_replace_ieops-2552.svg["Rimozione di una ventola dal chassis"]

. Far scorrere la ventola sostitutiva nello slot aperto dello chassis.
+
Allineare il connettore sulla ventola con la presa sulla scheda del circuito.

. Premere con decisione il connettore della ventola nella scheda a circuito stampato.
. link:reinstalling-sg120-and-sg1200-cover.html["Riposizionate il coperchio superiore sull'apparecchio"], e premere il fermo verso il basso per fissare il coperchio in posizione.
. link:power-sg120-and-sg1200-off-on.html["Accendere l'apparecchio"] e monitorare i LED dell'apparecchio e i codici di avvio.
+
Utilizzare l'interfaccia BMC per monitorare lo stato di avvio.

. Verificare che il nodo appliance sia visualizzato in Grid Manager e che non vengano visualizzati avvisi.


Dopo aver sostituito il componente, restituire il componente difettoso a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Consultare la  https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione dei pezzi"^] pagina per ulteriori informazioni.
