---
sidebar: sidebar 
permalink: storagegrid-enable.html 
keywords: storagegrid, how to enable, third-party solutions, tools, applications, examples 
summary: Scopri come testare e abilitare le applicazioni nel tuo ambiente StorageGRID. 
---
= Soluzioni e risorse StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vai a https://docs.netapp.com/us-en/storagegrid-enable/index.html["Soluzioni e risorse StorageGRID"^] per scoprire come testare e abilitare le applicazioni nel tuo ambiente StorageGRID .

* Soluzioni e risorse StorageGRID * fornisce esempi e manuali che ampliano la documentazione del prodotto presente in questo sito e descrivono alcuni passaggi successivi nella valutazione e nell'integrazione con StorageGRID.

Alcune delle informazioni incluse:

* Elenco delle soluzioni di terze parti validate per le release StorageGRID precedenti e correnti.
* Guide alle funzionalità del prodotto. Ad esempio, queste guide forniscono tutte le informazioni necessarie per creare pool di storage cloud.
* Guide agli strumenti e alle applicazioni.
* Esempi di API per l'utilizzo di funzionalità StorageGRID come la crittografia S3 e il blocco oggetti S3.

