---
sidebar: sidebar 
permalink: whats-new-appliances.html 
keywords: storagegrid, appliance, whats new 
summary: Scopri le novità di questo sito di documentazione. 
---
= Novità negli apparecchi StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità sugli appliance StorageGRID .



== Apparecchiature di servizio SG120 e SG1200

I nuovi appliance di servizio StorageGRID SG120 e SG1200 rappresentano un aggiornamento hardware evolutivo che offre prestazioni amministrative e di bilanciamento del carico migliorate. Consultare link:./installconfig/hardware-description-sg120-and-1200.html["SG120 e SG1200 services appliance: Panoramica"] per ulteriori informazioni.



== Appliance SGF6212

Il nuovo appliance di storage StorageGRID SGF6212 presenta un design compatto con compute controller e storage controller integrati in uno chassis 1U. L'appliance supporta 12 unità SSD NVMe in un RAID che fornisce storage a oggetti resiliente. Vedi link:installconfig/hardware-description-sg6200.html["Appliance SGF6212: Panoramica"] per saperne di più.



== Appliance SG6260

Il nuovo appliance StorageGRID SG6260 include un compute controller e uno shelf storage controller che contiene due storage controller e 60 dischi, oltre a due unità SSD NVMe per la cache. Opzionalmente, è possibile aggiungere shelf di espansione da 60 dischi all'SG6260. Consultare link:./installconfig/hardware-description-sg6200.html["Apparecchi SGF6200: Panoramica"] per ulteriori informazioni.



== La rete client può essere configurata senza un indirizzo IP

Ora è possibile abilitare la rete client senza specificare un indirizzo IP.  Ciò consente alla rete client di avere interfacce VLAN configurate in StorageGRID senza richiedere un indirizzo IP aggiuntivo per l'interfaccia stessa. Fare riferimento a link:.//installconfig/setting-ip-configuration.html["Configurare gli indirizzi IP StorageGRID"] .



== Numeri di versione per il software StorageGRID e Appliance Installer allineati

Con la versione 12.0 di StorgeGRID, il numero di versione di StorageGRID Appliance Installer corrisponde alla versione del software StorageGRID .  Gli utenti non devono più capire quali versioni funzionano insieme. Fare riferimento a link:./installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["Verificare e aggiornare la versione del programma di installazione dell'appliance StorageGRID"] .



== Informazioni BMC

Sono ora disponibili informazioni dettagliate sull'utilizzo dell'interfaccia BMC dell'appliance StorageGRID . Fare riferimento a link:./commonhardware/use-bmc.html["Utilizzo del BMC (Baseboard Management Controller) dell'appliance StorageGRID"] .
