---
permalink: sg6200/replacing-fan-in-sg6200.html 
sidebar: sidebar 
keywords: storagegrid, sgf6212, sg6200-cn, sg6260, storage appliance, Replacing, replace, fan, remove, removing, removal, install, installing 
summary: 'L"appliance SGF6212 e il controller SG6200-CN sono dotati di sette ventole di raffreddamento. Se una delle ventole si guasta, è necessario sostituirla il prima possibile per garantire un raffreddamento adeguato dell"appliance.' 
---
= Sostituire la ventola in un SGF6212 o SG6200-CN (SG6260)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'appliance SGF6212 e il controller SG6200-CN sono dotati di sette ventole di raffreddamento. Se una delle ventole si guasta, è necessario sostituirla il prima possibile per garantire un raffreddamento adeguato dell'appliance.

.A proposito di questa attività
Per evitare interruzioni del servizio, verificare che tutti gli altri nodi storage siano collegati alla griglia prima di iniziare la sostituzione della ventola o sostituire la ventola durante una finestra di manutenzione programmata in caso di accettabili periodi di interruzione del servizio. Vedere le informazioni su https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states["monitoraggio degli stati di connessione del nodo"^].


CAUTION: Se è stata utilizzata una regola ILM che crea solo una copia di un oggetto, è necessario sostituire la ventola durante una finestra di manutenzione pianificata poiché durante questa procedura potrebbe essere temporaneamente perso l'accesso a tali oggetti. Vedere informazioni su https://docs.netapp.com/us-en/storagegrid/ilm/why-you-should-not-use-single-copy-replication.html["perché non utilizzare la replica a copia singola"^].

Il nodo dell'appliance non sarà accessibile durante la sostituzione della ventola.


NOTE: Ciascuna delle due unità di alimentazione contiene anche una ventola. Le ventole dell'alimentatore non sono incluse in questa procedura.

.Prima di iniziare
* Si dispone della ventola sostitutiva corretta.
* Lo hai fatto link:verify-component-to-replace.html["determinata la posizione della ventola da sostituire"].
* Ti trovi link:locating-sg6200-in-data-center.html["individuare fisicamente l'appliance SGF6212 o il controller SG6200-CN"] nella situazione in cui devi sostituire la ventola nel data center.
+

NOTE: A link:power-sg6200-off-on.html#shut-down-the-sgf6212-appliance-or-sg6200-cn-controller["spegnimento controllato dell'apparecchio"] è necessario prima di rimuovere l'apparecchio dal rack.

* Hai scollegato tutti i cavi e link:reinstalling-sg6200-cover.html["rimuovere il coperchio dell'apparecchio"].
* Hai confermato che le altre ventole sono installate e in esecuzione.


.Fasi
. Avvolgere l'estremità del braccialetto ESD intorno al polso e fissare l'estremità del fermaglio a una messa a terra metallica per evitare scariche elettrostatiche.
. Individuare la ventola da sostituire.
+
Le sette ventole sono nelle seguenti posizioni nello chassis (metà anteriore dell'appliance StorageGRID con il coperchio superiore rimosso mostrata):

+
image::../media/drw_fan_position_ieops-2614.svg[Posizioni delle ventole nello chassis StorageGRID]

+
|===
| Posizione del chassis | Gruppo ventola 


 a| 
1
 a| 
Fan_SYS0



 a| 
2
 a| 
Fan_SYS1



 a| 
3
 a| 
Fan_SYS2



 a| 
4
 a| 
Fan_SYS3



 a| 
5
 a| 
Fan_SYS4



 a| 
6
 a| 
Fan_SYS5



 a| 
7
 a| 
Fan_SYS6

|===
. Utilizzando le linguette blu sulla ventola, estrarre la ventola guasta dal telaio.
+
image:../media/drw_s2025_fan_replace_ieops-2552.svg["Rimozione di una ventola dal chassis"]

. Far scorrere la ventola sostitutiva nello slot aperto dello chassis.
+
Allineare il connettore sulla ventola con la presa sulla scheda del circuito.

. Premere con decisione il connettore della ventola nella scheda a circuito stampato.
. link:reinstalling-sg6200-cover.html["Riposizionate il coperchio superiore sull'apparecchio"], e premere il fermo verso il basso per fissare il coperchio in posizione.
. link:power-sg6200-off-on.html["Accendere l'apparecchio"] e monitorare i LED dell'apparecchio e i codici di avvio.
+
Utilizzare l'interfaccia BMC per monitorare lo stato di avvio.

. Verificare che il nodo appliance sia visualizzato in Grid Manager e che non vengano visualizzati avvisi.


Dopo aver sostituito il componente, restituire il componente difettoso a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Consultare la  https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione dei pezzi"^] pagina per ulteriori informazioni.
