---
permalink: sg6200/replacing-sg6200-cn-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg6200, storage node, storage appliance, Replacing, replace, sg6200-cn, controller, remove, removing, removal, install, installing, installation 
summary: Potrebbe essere necessario sostituire il controller SG6200-CN se non funziona in modo ottimale o se si è guastato. 
---
= Sostituire il controller SG6200-CN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario sostituire il controller SG6200-CN se non funziona in modo ottimale o se si è guastato.

.A proposito di questa attività
Il nodo di storage dell'appliance non sarà accessibile quando si sostituisce lo storage controller SG6200-CN. Se lo storage controller SG6200-CN funziona sufficientemente, è possibile eseguire un arresto controllato all'inizio di questa procedura.


NOTE: Se si sostituisce il controller prima di installare il software StorageGRID, potrebbe non essere possibile accedere al programma di installazione dell'appliance StorageGRID subito dopo aver completato questa procedura. Sebbene sia possibile accedere al programma di installazione dell'appliance StorageGRID da altri host sulla stessa sottorete dell'appliance, non è possibile accedervi da host su altre subnet. Questa condizione dovrebbe risolversi entro 15 minuti (quando qualsiasi voce della cache ARP per il timeout del controller originale), oppure è possibile cancellare immediatamente la condizione cancellando manualmente le vecchie voci della cache ARP dal router o gateway locale.

.Prima di iniziare
* Si dispone di un controller sostitutivo con lo stesso numero di parte del controller che si sta sostituendo. Controllare le etichette attaccate alla parte anteriore delle centraline per confermare che i numeri di parte corrispondano.
* Sono presenti etichette per identificare ciascun cavo collegato al controller.
* Il controller da sostituire nel data center è stato fisicamente posizionato.
+
link:locating-sg6200-in-data-center.html["Individuare il controller nel data center"]



.Fasi
. Visualizzare le configurazioni correnti dell'appliance e registrarle.
+
.. Accedere all'apparecchio da sostituire:
+
... Immettere il seguente comando: `ssh admin@_grid_node_IP_`
... Immettere la password elencata in `Passwords.txt` file.
... Immettere il seguente comando per passare a root: `su -`
... Immettere la password elencata in `Passwords.txt` file.
+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.



.. Inserire: `*run-host-command ipmitool lan print*` Per visualizzare le configurazioni BMC correnti per l'appliance.


. Se il controller SG6200-CN funziona a sufficienza per consentire uno spegnimento controllato, link:power-sg6200-off-on.html["Spegnere il controller SG6200-CN"].
. Se una delle interfacce di rete di questo dispositivo StorageGRID è configurata per DHCP, potrebbe essere necessario aggiornare le assegnazioni permanenti del lease DHCP sui server DHCP per fare riferimento agli indirizzi MAC del dispositivo sostitutivo. L'aggiornamento garantisce che all'appliance siano assegnati gli indirizzi IP previsti.
. Rimuovere e sostituire il controller SG6200-CN:
+
.. Etichettare e scollegare i cavi.
+

CAUTION: Per evitare prestazioni degradate, non attorcigliare, piegare, pizzicare o salire sui cavi.

.. Rimuovere il controller guasto dal cabinet o dal rack.
.. Installare il controller sostitutivo nel cabinet o nel rack.
.. Sostituire i cavi.
.. Accendere il controller e controllare i LED del controller.


. Se l'appliance sostituita ha abilitato la crittografia dell'unità hardware per le unità SED, è necessario https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/optional-enabling-node-encryption.html#access-an-encrypted-drive["immettere la passphrase di crittografia dell'unità"] per accedere ai dischi crittografati al primo avvio dell'appliance sostitutiva.
. Se l'appliance in cui è stato sostituito il controller utilizzava un server di gestione delle chiavi (KMS) per crittografare i dati, potrebbe essere necessaria una configurazione aggiuntiva prima che il nodo possa unirsi alla griglia. Se il nodo non si unisce automaticamente alla griglia, assicurarsi che queste impostazioni di configurazione siano state trasferite al nuovo controller e configurare manualmente le impostazioni che non hanno la configurazione prevista:
+
** link:../installconfig/configuring-network-links.html["Configurare i collegamenti di rete"]
** link:../installconfig/setting-ip-configuration.html["Configurare gli indirizzi IP StorageGRID"]
** https://docs.netapp.com/us-en/storagegrid/admin/kms-overview-of-kms-and-appliance-configuration.html#set-up-the-appliance["Configurare la crittografia dei nodi per l'appliance"^]


. Accedere all'appliance con il controller sostituito:
+
.. Immettere il seguente comando: `ssh admin@_grid_node_IP_`
.. Immettere la password elencata in `Passwords.txt` file.
.. Immettere il seguente comando per passare a root: `su -`
.. Immettere la password elencata in `Passwords.txt` file.


. Ripristinare la connettività di rete BMC per l'appliance. Sono disponibili due opzioni:
+
** Utilizzare IP statico, netmask e gateway
** Utilizzare DHCP per ottenere un IP, una netmask e un gateway
+
... Per ripristinare la configurazione BMC in modo che utilizzi un IP statico, una netmask e un gateway, immettere i seguenti comandi:
+
`*run-host-command ipmitool lan set 1 ipaddr _Appliance_IP_*`

+
`*run-host-command ipmitool lan set 1 netmask _Netmask_IP_*`

+
`*run-host-command ipmitool lan set 1 defgw ipaddr _Default_gateway_*`

... Per ripristinare la configurazione BMC in modo che utilizzi DHCP per ottenere un IP, una netmask e un gateway, immettere il seguente comando:
+
`*run-host-command ipmitool lan set 1 ipsrc dhcp*`





. Dopo aver ripristinato la connettività di rete BMC, connettersi all'interfaccia BMC per controllare e ripristinare eventuali configurazioni BMC personalizzate aggiuntive applicate. Ad esempio, è necessario confermare le impostazioni per le destinazioni dei messaggi trap SNMP e le notifiche e-mail. Vedere link:../installconfig/configuring-bmc-interface.html["Configurare l'interfaccia BMC"].
. Verificare che il nodo appliance sia visualizzato in Grid Manager e che non vengano visualizzati avvisi.


Dopo aver sostituito il componente, restituire il componente difettoso a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Consultare la  https://mysupport.netapp.com/site/info/rma["Restituzione e sostituzione dei pezzi"^] pagina per ulteriori informazioni.
