---
permalink: installconfig/automating-configuration-of-storagegrid.html 
sidebar: sidebar 
keywords: automate, automating, automation, automatic, configuration, configure 
summary: Dopo aver installato e configurato i nodi di rete, è possibile automatizzare la configurazione del sistema StorageGRID. 
---
= Automatizzare la configurazione di StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver installato e configurato i nodi di rete, è possibile automatizzare la configurazione del sistema StorageGRID.

.Prima di iniziare
* Si conosce la posizione dei seguenti file dall'archivio di installazione.
+
[cols="1a,1a"]
|===
| Nome file | Descrizione 


| configure-storagegrid.py  a| 
Script Python utilizzato per automatizzare la configurazione



| configure-storagegrid.sample.json  a| 
File di configurazione di esempio da utilizzare con lo script



| configure-storagegrid.blank.json  a| 
File di configurazione vuoto da utilizzare con lo script

|===
* È stato creato un `configure-storagegrid.json` file di configurazione. Per creare questo file, è possibile modificare il file di configurazione di esempio (`configure-storagegrid.sample.json`) o il file di configurazione vuoto (`configure-storagegrid.blank.json`).


.A proposito di questa attività
È possibile utilizzare `configure-storagegrid.py` Script Python e il `configure-storagegrid.json` File di configurazione per automatizzare la configurazione del sistema StorageGRID.


NOTE: È inoltre possibile configurare il sistema utilizzando https://docs.netapp.com/us-en/storagegrid-118/primer/exploring-grid-manager.html["Grid Manager"^] o il link:overview-of-installation-rest-apis.html["API di installazione"].

.Fasi
. Accedere alla macchina Linux in uso per eseguire lo script Python.
. Passare alla directory in cui è stato estratto l'archivio di installazione.
+
Ad esempio: +
`cd StorageGRID-Webscale-_version/platform_`

+
dove `_platform_` è `debs`, `rpms`, o. `vsphere`.

. Eseguire lo script Python e utilizzare il file di configurazione creato.
+
Ad esempio:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Al termine
Un pacchetto di ripristino `.zip` il file viene generato durante il processo di configurazione e scaricato nella directory in cui si esegue il processo di installazione e configurazione. È necessario eseguire il backup del file del pacchetto di ripristino in modo da poter ripristinare il sistema StorageGRID in caso di guasto di uno o più nodi della griglia. Ad esempio, copiarla in una posizione di rete sicura e di backup e in una posizione di cloud storage sicura.


CAUTION: Il file del pacchetto di ripristino deve essere protetto perché contiene chiavi di crittografia e password che possono essere utilizzate per ottenere dati dal sistema StorageGRID.

Se si specifica che devono essere generate password casuali, è necessario estrarre `Passwords.txt` E cercare le password necessarie per accedere al sistema StorageGRID.

[listing]
----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
Il sistema StorageGRID viene installato e configurato quando viene visualizzato un messaggio di conferma.

[listing]
----
StorageGRID has been configured and installed.
----