---
permalink: installconfig/configuring-bmc-interface.html 
sidebar: sidebar 
keywords: BMC, baseboard management controller, configure, setup, set up 
summary: 'L"interfaccia utente del controller di gestione della scheda madre (BMC) su SG6200, SG6100, SG6000 o sull"appliance di servizio fornisce informazioni sullo stato dell"hardware e consente di configurare le impostazioni SNMP e altre opzioni per le appliance.' 
---
= Interfaccia BMC per gli appliance StorageGRID SG6000, SG6100 e SG6200 e per gli appliance di servizi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente del controller di gestione della scheda madre (BMC) fornisce informazioni sullo stato dell'hardware e consente l'accesso di basso livello all'hardware per la configurazione, il monitoraggio e la diagnostica dell'appliance.

È possibile utilizzare il BMC per:

* Risolvi i problemi di installazione dell'hardware
* Configurare le impostazioni SNMP
* Determina lo stato di alimentazione del tuo apparecchio
* Controlla il LED di identificazione del tuo apparecchio


Le seguenti appliance StorageGRID supportano l'interfaccia BMC:

* SG100
* SG110
* SG120
* SG1000
* SG1100
* SG1200
* SGF6024
* SGF6112
* SGF6212
* SG6060
* SG6160
* SG6260


Se stai installando il tuo dispositivo, segui le procedure seguenti per configurare il BMC:

* link:../installconfig/changing-root-password-for-bmc-interface.html["Modificare la password admin o root per l'interfaccia BMC"]
* link:../installconfig/setting-ip-address-for-bmc-management-port.html["Impostare l'indirizzo IP per la porta di gestione BMC"]
* link:../installconfig/accessing-bmc-interface.html["Accedere all'interfaccia BMC"]
* link:../installconfig/configuring-snmp-settings-for-bmc.html["Configurare le impostazioni SNMP"]
* link:../installconfig/setting-up-email-notifications-for-alerts.html["Impostare le notifiche e-mail per gli avvisi BMC"]


Se hai già installato l'appliance in una griglia e su di essa è in esecuzione il software StorageGRID, utilizza le seguenti procedure:

* link:../commonhardware/placing-appliance-into-maintenance-mode.html["Impostare l'apparecchio in modalità di manutenzione"] Per accedere al programma di installazione dell'appliance StorageGRID.
* Consultare link:../installconfig/setting-ip-address-for-bmc-management-port.html["Impostare l'indirizzo IP per la porta di gestione BMC"] per informazioni sull'accesso all'interfaccia BMC utilizzando StorageGRID Appliance Installer.


Per ulteriori informazioni sulle funzionalità utilizzabili con il BMC dopo la configurazione, fare riferimento a link:../commonhardware/use-bmc.html["USA l'interfaccia BMC"] e al  https://kb.netapp.com/hybrid/StorageGRID/Platforms/How_to_use_StorageGRID_Appliance_BMC_with_vendor_supplied_user_guide["Guida utente di BMC"^].
