---
permalink: installconfig/configuring-hardware.html 
sidebar: sidebar 
keywords: storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: 'Dopo aver alimentato l"appliance, configurare le connessioni di rete che verranno utilizzate da StorageGRID. ' 
---
= Configurazione dell'hardware: Panoramica
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver alimentato l'appliance, configurare le connessioni di rete che verranno utilizzate da StorageGRID.



== Configurare le connessioni di rete richieste

Per tutte le appliance, è possibile eseguire diverse attività per configurare le connessioni di rete richieste, ad esempio:

* Accedere al programma di installazione dell'appliance
* Configurare i collegamenti di rete
* Verificare le connessioni di rete a livello di porta




== Configurazione aggiuntiva che potrebbe essere necessaria

A seconda dei tipi di appliance da configurare, potrebbe essere necessaria una configurazione hardware aggiuntiva.



=== Gestore di sistema di SANtricity

Per i modelli SG6160, SG6000, SG5800 e SG5700, è possibile configurare Gestione di sistema di SANtricity. Il software SANtricity viene utilizzato per monitorare l'hardware di queste appliance.



=== Interfaccia BMC

Le seguenti appliance dispongono di un'interfaccia BMC che deve essere configurata:

* SG100
* SG110
* SG1000
* SG1100
* SG6000
* SG6100




== Configurazione opzionale

* Appliance di storage
+
** Configurare Gestione di sistema di SANtricity (SG5700, SG5800, SG6000 e SG6100) il software che verrà utilizzato per monitorare l'hardware
** Modificare la modalità RAID
** link:../installconfig/accessing-bmc-interface.html["Accedere all'interfaccia BMC"] Per la centralina SG6000-CN o SG6100-CN


* Appliance di servizi
+
** link:../installconfig/accessing-bmc-interface.html["Accedere all'interfaccia BMC"] Per SG100, SG110, SG1000 e SG1100



