---
permalink: installconfig/configuring-hardware.html 
sidebar: sidebar 
keywords: storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: 'Dopo aver alimentato l"appliance, configurare le connessioni di rete che verranno utilizzate da StorageGRID. ' 
---
= Configura l'hardware dell'appliance StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver alimentato l'appliance, configurare le connessioni di rete che verranno utilizzate da StorageGRID.



== Configurazioni hardware richieste



=== Connessioni di rete

È necessario configurare e verificare le connessioni di rete richieste per tutti gli apparecchi:

* link:../installconfig/accessing-storagegrid-appliance-installer.html["Accedere al programma di installazione dell'appliance"]
* link:../installconfig/configuring-network-links.html["Configurare i collegamenti di rete"]
* link:../installconfig/verifying-port-level-network-connections.html["Verificare le connessioni di rete a livello di porta"]




=== Interfaccia BMC

È necessario link:../installconfig/configuring-bmc-interface.html["configurare l'interfaccia del controller di gestione della scheda madre (BMC)"] se si sta installando uno dei seguenti apparecchi:

* SG100
* SG110
* SG120
* SG1000
* SG1100
* SG1200
* SGF6024
* SGF6112
* SGF6212
* SG6060
* SG6160
* SG6260


È possibile utilizzare l'interfaccia BMC per configurare SNMP e altre impostazioni di basso livello per i propri dispositivi. Consente inoltre di risolvere i problemi di installazione hardware, determinare lo stato di alimentazione del dispositivo e controllare il LED di identificazione sul dispositivo stesso.

Per ulteriori informazioni sulle funzionalità utilizzabili con il BMC, consultare link:../commonhardware/use-bmc.html["USA l'interfaccia BMC"].



== Configurazioni hardware opzionali



=== Gestore di sistema di SANtricity

Puoi link:../installconfig/accessing-and-configuring-santricity-system-manager.html["configurare SANtricity System Manager"] se possiedi uno dei seguenti appliance:

* SG5712
* SG5760
* SG5812
* SG5860
* SGF6024
* SG6060
* SG6160
* SG6260


Il software SANtricity System Manager consente di:

* Monitora i dati sulle prestazioni del sistema, lo stato dei componenti hardware e le funzioni di supporto per il tuo appliance
* Gestisci le chiavi di sicurezza delle unità, gli avvisi SNMP e syslofg e le password di amministratore per l'accesso a SANtricity System Manager
* Configurare l'accesso alla E-Series AutoSupport




=== Abilita crittografia di nodi o dischi

È possibile link:../installconfig/optional-enabling-node-encryption.html["abilita la crittografia del nodo o dell'unità"] proteggere le unità e i dischi presenti nell'apparecchio.



=== Modifica modalità RAID

È possibile link:../installconfig/optional-changing-raid-mode.html["modificare la modalità RAID del dispositivo di archiviazione"] per soddisfare le proprie esigenze di archiviazione e ripristino.

I seguenti dispositivi supportano la modifica della modalità RAID:

* SG5760
* SG5860
* SGF6024
* SG6060
* SG6160
* SG6260




=== Rimappare le porte di rete

È possibile link:../installconfig/optional-remapping-network-ports-for-appliance.html["rimappa le porte di rete sul tuo dispositivo"] ottimizzare le connessioni di rete.
