---
permalink: installconfig/deploying-appliance-storage-node.html 
sidebar: sidebar 
keywords: storage node, storage appliance, deploy node, deploying node, node, deploy, deploying 
summary: 'Dopo aver installato e configurato l"appliance di storage, è possibile implementarla come nodo di storage in un sistema StorageGRID. Quando si implementa un"appliance come nodo di storage, si utilizza il programma di installazione dell"appliance StorageGRID incluso nell"appliance.' 
---
= Implementare l'appliance Storage Node
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver installato e configurato l'appliance di storage, è possibile implementarla come nodo di storage in un sistema StorageGRID. Quando si implementa un'appliance come nodo di storage, si utilizza il programma di installazione dell'appliance StorageGRID incluso nell'appliance.

.Prima di iniziare
* Se si sta clonando un nodo appliance, continuare a seguire la procedura descritta in link:../commonhardware/appliance-node-cloning-procedure.html["cloning del nodo dell'appliance"] processo.
* L'apparecchio è stato installato in un rack o in un cabinet, collegato alla rete e acceso.
* I collegamenti di rete, gli indirizzi IP e il rimapping delle porte (se necessario) sono stati configurati per l'appliance utilizzando il programma di installazione dell'appliance StorageGRID.
+

NOTE: Il supporto per la rimappatura delle porte è obsoleto e verrà rimosso in una versione futura.  Per rimuovere le porte rimappate, fare riferimento a https://docs.netapp.com/us-en/storagegrid/maintain/removing-port-remaps.html["Rimuovere le rimappature delle porte sugli apparecchi StorageGRID"^] .

* Conosci uno degli indirizzi IP assegnati al controller di calcolo dell'appliance. È possibile utilizzare l'indirizzo IP per qualsiasi rete StorageGRID collegata.
* Il nodo amministrativo primario per il sistema StorageGRID è stato implementato.
* Tutte le subnet della rete griglia elencate nella pagina di configurazione IP del programma di installazione dell'appliance StorageGRID sono state definite nell'elenco delle subnet della rete griglia nel nodo di amministrazione principale.
* Si dispone di un laptop di assistenza con un browser Web supportato.


.A proposito di questa attività
Ogni appliance di storage funziona come un singolo nodo di storage. Qualsiasi appliance può connettersi a Grid Network, Admin Network e Client Network

Per implementare un nodo di storage dell'appliance in un sistema StorageGRID, accedere al programma di installazione dell'appliance StorageGRID ed eseguire le seguenti operazioni:

* Specificare o confermare l'indirizzo IP del nodo di amministrazione primario e il nome del nodo di storage.
* Avviare l'implementazione e attendere la configurazione dei volumi e l'installazione del software.
* Quando l'installazione viene interrotta parzialmente attraverso le attività di installazione dell'appliance, l'installazione viene ripristinata accedendo a Grid Manager, approvando tutti i nodi Grid e completando i processi di installazione e implementazione di StorageGRID.



NOTE: Se è necessario implementare più nodi di appliance contemporaneamente, è possibile automatizzare il processo di installazione utilizzando il collegamento:./installconfig/automaticing-appliance-installation-and-Configuration.html#automatize-with-configure-sga-py-script[`configure-sga.py` Script di installazione dell'appliance].

* Se si sta eseguendo un'operazione di espansione o ripristino, seguire le istruzioni appropriate:
+
** Per aggiungere un nodo di archiviazione appliance a un sistema StorageGRID esistente, vedere le istruzioni per https://docs.netapp.com/us-en/storagegrid/expand/adding-grid-nodes-to-existing-site-or-adding-new-site.html["aggiunta di nodi griglia"^].
** Per distribuire un nodo di archiviazione dell'appliance come parte di un'operazione di ripristino, vedere le istruzioni https://docs.netapp.com/us-en/storagegrid/maintain/recovering-storagegrid-appliance-storage-node.html["Ripristino di un nodo di storage dell'appliance"^].




.Fasi
. Aprire un browser e inserire uno degli indirizzi IP del controller di elaborazione dell'appliance. +
`*https://_Controller_IP_:8443*`
+
Viene visualizzata la pagina iniziale del programma di installazione dell'appliance StorageGRID.

. Selezionare il *tipo di nodo*. Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/storagegrid/primer/what-storage-node-is.html#types-of-storage-nodes["Tipi di nodi storage"].
+

NOTE: È possibile selezionare solo i metadati durante l'implementazione dell'appliance. Se è selezionato solo metadati come tipo di nodo di archiviazione, non è possibile modificarlo dopo la distribuzione dell'appliance.

. Nel campo *Node name* (Nome nodo), specificare il nome di sistema che si desidera utilizzare per il nodo dell'appliance e fare clic su *Save* (Salva).
+
Il nome visualizzato qui sarà il nome di sistema del nodo appliance.  I nomi di sistema sono necessari per le operazioni interne StorageGRID e non possono essere modificati.  Per modificare il nome visualizzato di un nodo appliance, vedere https://docs.netapp.com/us-en/storagegrid/maintain/rename-grid-site-node.html#how-to-rename-grid-sites-or-nodes["Come rinominare la griglia, i siti o i nodi"^] .

. Nella sezione *Primary Admin Node Connection* (connessione nodo amministratore primario), determinare se è necessario specificare l'indirizzo IP per il nodo amministratore primario.
+
Se in precedenza sono stati installati altri nodi in questo data center, il programma di installazione dell'appliance StorageGRID è in grado di rilevare automaticamente questo indirizzo IP, supponendo che il nodo di amministrazione primario o almeno un altro nodo della griglia con ADMIN_IP configurato sia presente sulla stessa sottorete.

. Se questo indirizzo IP non viene visualizzato o se è necessario modificarlo, specificare l'indirizzo:
+
[cols="1a,2a"]
|===
| Opzione | Descrizione 


 a| 
Immissione manuale dell'IP
 a| 
.. Deselezionare la casella di controllo *Enable Admin Node Discovery* (attiva rilevamento nodo amministratore).
.. Inserire l'indirizzo IP manualmente.
.. Fare clic su *Save* (Salva).
.. Attendere che lo stato di connessione del nuovo indirizzo IP diventi pronto.




 a| 
Rilevamento automatico di tutti i nodi amministrativi primari connessi
 a| 
.. Selezionare la casella di controllo *Enable Admin Node Discovery* (attiva rilevamento nodo amministratore).
.. Attendere che venga visualizzato l'elenco degli indirizzi IP rilevati.
.. Selezionare il nodo di amministrazione principale per la griglia in cui verrà implementato il nodo di storage dell'appliance.
.. Fare clic su *Save* (Salva).
.. Attendere che lo stato di connessione del nuovo indirizzo IP diventi pronto.


|===
. Nella sezione *Installazione*, verificare che lo stato corrente sia "Pronto per avviare l'installazione di `_node name_` Nella griglia con nodo di amministrazione primario `_admin_ip_` " E che il pulsante *Avvia installazione* sia attivato.
+
Se il pulsante *Avvia installazione* non è attivato, potrebbe essere necessario modificare la configurazione di rete o le impostazioni della porta. Per istruzioni, consultare le istruzioni di manutenzione dell'apparecchio.

+

NOTE: Se si sta implementando l'appliance Storage Node come destinazione di clonazione del nodo, interrompere il processo di implementazione e continuare con
link:../commonhardware/appliance-node-cloning-procedure.html["procedura di cloning del nodo"].

. Dalla home page del programma di installazione dell'appliance StorageGRID, fare clic su *Avvia installazione*.
+
Lo stato corrente cambia in "`Installazione in corso,''" e in link:../installconfig/monitoring-appliance-installation.html["Pagina Installazione monitor"] viene visualizzato.

+

NOTE: Per accedere manualmente alla pagina Installazione monitor, fare clic su *Installazione monitor*.

. Se la griglia include più nodi storage dell'appliance, ripetere questi passaggi per ogni appliance.
+

NOTE: Se è necessario implementare più nodi di storage di appliance contemporaneamente, è possibile automatizzare il processo di installazione utilizzando il collegamento:./installconfig/automaticing-appliance-installation-and-Configuration.html#automatizza-with-configure-sga-py-script[`configure-sga.py` Script di installazione dell'appliance].


