---
permalink: installconfig/monitoring-appliance-installation.html 
sidebar: sidebar 
keywords: appliance, installation, install, progress, monitor, status 
summary: 'Il programma di installazione dell"appliance StorageGRID indica lo stato fino al completamento dell"installazione. Una volta completata l"installazione del software, l"appliance viene riavviata.' 
---
= Installazione dell'appliance di monitoraggio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il programma di installazione dell'appliance StorageGRID indica lo stato fino al completamento dell'installazione. Una volta completata l'installazione del software, l'appliance viene riavviata.

.Fasi
[role="tabbed-block"]
====
.Appliance di storage
--
. Per monitorare l'avanzamento dell'installazione, fare clic su *Monitor Installation* (Installazione monitor).
+
La pagina Monitor Installation (Installazione monitor) mostra lo stato di avanzamento dell'installazione.

+
La barra di stato blu indica l'attività attualmente in corso. Le barre di stato verdi indicano le attività completate correttamente.

+

NOTE: Il programma di installazione garantisce che le attività completate in un'installazione precedente non vengano rieseguite. Se si esegue nuovamente un'installazione, tutte le attività che non devono essere rieseguite vengono visualizzate con una barra di stato verde e lo stato "`Skipped`".

. Esaminare i progressi delle prime due fasi di installazione.
+
*1. Configurare lo storage*

+
Durante questa fase, il programma di installazione si connette al controller dello storage, cancella qualsiasi configurazione esistente, crea RAID in base alla modalità RAID configurata, alloca volumi per il software StorageGRID e lo storage dei dati a oggetti e configura le impostazioni dell'host.

+
*2. Installare il sistema operativo*

+
In questa fase, il programma di installazione copia l'immagine del sistema operativo di base per StorageGRID nell'appliance.

. Continuare a monitorare l'avanzamento dell'installazione finché la fase *Install StorageGRID* non si interrompe e sulla console incorporata viene visualizzato un messaggio che richiede di approvare questo nodo sul nodo di amministrazione tramite Grid Manager; quindi, passare al passaggio successivo.
. https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Accedere a Grid Manager"^]del nodo Amministratore primario, approvare il nodo di archiviazione in sospeso e completare il processo di installazione StorageGRID .
+
Facendo clic su *Install* (Installa) da Grid Manager, viene completata la fase 3 e viene avviata la fase 4, *Finalize Installation* (completamento dell'installazione). Al termine della fase 4, il controller viene riavviato.



Al termine di tutte le fasi di installazione, chiudere la finestra.

--
.Appliance di servizi
--
. Per monitorare l'avanzamento dell'installazione, fare clic su *Monitor Installation* (Installazione monitor).
+
La pagina Monitor Installation (Installazione monitor) mostra lo stato di avanzamento dell'installazione.

+
La barra di stato blu indica l'attività attualmente in corso. Le barre di stato verdi indicano le attività completate correttamente.

+

NOTE: Il programma di installazione garantisce che le attività completate in un'installazione precedente non vengano rieseguite. Se si esegue nuovamente un'installazione, tutte le attività che non devono essere rieseguite vengono visualizzate con una barra di stato verde e lo stato "`Skipped`".

. Esaminare i progressi delle prime due fasi di installazione.
+
*1. Configurare lo storage*

+
In questa fase, il programma di installazione cancella qualsiasi configurazione esistente dai dischi dell'appliance e configura le impostazioni dell'host.

+
*2. Installare il sistema operativo*

+
In questa fase, il programma di installazione copia l'immagine del sistema operativo di base per StorageGRID nell'appliance.

. Continuare a monitorare l'avanzamento dell'installazione fino a quando non si verifica una delle seguenti procedure:
+
** Per tutti i nodi dell'appliance, ad eccezione del nodo di amministrazione primario, la fase di installazione StorageGRID si interrompe e sulla console incorporata viene visualizzato un messaggio che richiede di approvare questo nodo sul nodo di amministrazione utilizzando https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Grid Manager"^] ; quindi, vai al passaggio successivo.
** Per l'installazione di Admin Node primario dell'appliance, non è necessario approvare il nodo. L'apparecchio viene riavviato. È possibile saltare la fase successiva.
+

NOTE: Durante l'installazione di un nodo amministrativo primario dell'appliance, viene visualizzata una quinta fase per caricare il programma di installazione StorageGRID (la schermata di esempio mostra solo le prime quattro fasi). Se il caricamento del programma di installazione di StorageGRID (quinta fase) è in corso per più di 10 minuti, aggiornare manualmente la pagina Web.



. https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Accedere a Grid Manager"^] Del nodo Amministratore primario, approvare il nodo griglia in sospeso e completare il processo di installazione di StorageGRID.
+
Facendo clic su *Install* (Installa) da Grid Manager, viene completata la fase 3 e viene avviata la fase 4, *Finalize Installation* (completamento dell'installazione). Al termine della fase 4, l'appliance viene riavviato.



Al termine di tutte le fasi di installazione, chiudere la finestra.

--
====