---
permalink: sg5700/index.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: 'Potrebbe essere necessario aggiornare il software del sistema operativo SANtricity sul controller E2800, modificare la configurazione del collegamento Ethernet del controller E5700SG, sostituire il controller E2800 o il controller E5700SG o sostituire componenti specifici. Le procedure descritte in questa sezione presuppongono che l"appliance sia già stata implementata come nodo di storage in un sistema StorageGRID.' 
---
= Manutenzione dell'appliance SG5700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario aggiornare il software del sistema operativo SANtricity sul controller E2800, modificare la configurazione del collegamento Ethernet del controller E5700SG, sostituire il controller E2800 o il controller E5700SG o sostituire componenti specifici. Le procedure descritte in questa sezione presuppongono che l'appliance sia già stata implementata come nodo di storage in un sistema StorageGRID.

Le procedure specifiche per la manutenzione dell'appliance SG5700 sono descritte in questa sezione.

Vedere link:../commonhardware/index.html["Procedure comuni"] per le procedure di manutenzione utilizzate da tutti gli appliance.

Vedere link:../installconfig/configuring-hardware.html["Configurare l'hardware"] per le procedure di manutenzione eseguite anche durante l'installazione e la configurazione iniziale dell'appliance.
