---
permalink: sg5800/replace-controller-5800sg.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Sostituire il controller StorageGRID SG5800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Potrebbe essere necessario sostituire il controller SG5800 se non funziona in modo ottimale o se è guasto.

.Prima di iniziare
* Si dispone di un controller sostitutivo con lo stesso numero di parte del controller che si sta sostituendo.
* Sono presenti etichette per identificare ciascun cavo collegato al controller.


.A proposito di questa attività
Non sarà possibile accedere al nodo di archiviazione dell'appliance quando si sostituisce il controller.  Se il controller SG5800 funziona correttamente, è possibile eseguire uno spegnimento controllato all'inizio di questa procedura.


NOTE: Se si sostituisce il controller prima di installare il software StorageGRID, potrebbe non essere possibile accedere al programma di installazione dell'appliance StorageGRID subito dopo aver completato questa procedura. Sebbene sia possibile accedere al programma di installazione dell'appliance StorageGRID da altri host sulla stessa sottorete dell'appliance, non è possibile accedervi dagli host presenti su altre sottoreti. Questa condizione dovrebbe risolversi entro 15 minuti (quando qualsiasi voce della cache ARP per il timeout del controller originale), oppure è possibile cancellare immediatamente la condizione cancellando manualmente le vecchie voci della cache ARP dal router o gateway locale.

.Fasi
. Spegnere il controller SG5800.
+
.. Accedere al nodo Grid:
+
... Immettere il seguente comando: `ssh admin@grid_node_IP`
... Immettere la password elencata in `Passwords.txt` file.
... Immettere il seguente comando per passare a root: `su -`
... Immettere la password elencata in `Passwords.txt` file.
+
Una volta effettuato l'accesso come root, il prompt cambia da `$` a. `#`.





. Arrestare il controller SG5800:
+
*`shutdown -h now`*

. Se le reti StorageGRID collegate al controller utilizzano server DHCP:
+
.. Annotare gli indirizzi MAC delle porte del controller sostitutivo (indicati sulle etichette del controller).
.. Chiedere all'amministratore di rete di aggiornare le impostazioni dell'indirizzo IP del controller originale in modo che riflettano gli indirizzi MAC del controller sostitutivo.
+

NOTE: Prima di inserire il controller sostitutivo nell'appliance, è necessario assicurarsi che gli indirizzi IP del controller originale siano stati aggiornati.  In caso contrario, il controller otterrà nuovi indirizzi IP DHCP all'avvio e potrebbe non essere in grado di riconnettersi a StorageGRID.  Questo passaggio si applica a tutte le reti StorageGRID collegate al controller.



. Rimuovere il controller dall'apparecchio:
+
.. Indossare un braccialetto ESD o adottare altre precauzioni antistatiche.
.. Etichettare i cavi, quindi scollegarli.
+

NOTE: Per evitare di danneggiare le prestazioni, non torcere, piegare, schiacciare o salire sui cavi.
Rilasciare il controller dall'apparecchio premendo il fermo sull'impugnatura della camma fino a rilasciarlo, quindi aprire l'impugnatura della camma verso destra.

.. Estrarre il controller dall'apparecchio con due mani e la maniglia della camma.
+

NOTE: Utilizzare sempre due mani per sostenere il peso del controller.



. Installare il controller sostitutivo nell'appliance.
+
.. Capovolgere il controller, in modo che il coperchio rimovibile sia rivolto verso il basso.
.. Con la maniglia della camma in posizione aperta, far scorrere il controller fino in fondo nell'apparecchio.
.. Spostare la maniglia della camma verso sinistra per bloccare il controller in posizione.
.. Sostituire i cavi.


. Dopo il riavvio del controller e la reintegrazione dell'appliance nella griglia, verificare che il nodo di archiviazione dell'appliance sia visualizzato in Grid Manager e che non siano presenti allarmi.


Dopo aver sostituito il componente, restituire il componente guasto a NetApp, come descritto nelle istruzioni RMA fornite con il kit. Vedere https://mysupport.netapp.com/site/info/rma[" di restituzione della parte; sostituzioni"] per ulteriori informazioni.
