---
sidebar: sidebar 
permalink: commonhardware/storage-node-maintenance.html 
keywords: stub, layered 
summary: Manutenzione del nodo di storage. 
---
= Manutenzione del nodo di storage
:allow-uri-read: 


[role="lead"]
Manutenzione del nodo di storage. Questo ha senso consolidare?

(Nuovo argomento introduttivo)



== Aggiornamento del sistema operativo SANtricity sui controller di storage (nodi di storage)

(Ritiro dall'argomento dell'appliance esistente - necessità di combinare)



=== Aggiornamento del sistema operativo SANtricity sui controller di storage mediante Grid Manager

(Ritiro dall'argomento dell'appliance esistente - necessità di combinare)



=== Aggiornamento del sistema operativo SANtricity sui controller di storage utilizzando la modalità di manutenzione

(Ritiro dall'argomento dell'appliance esistente - necessità di combinare)



== Aggiornamento del firmware del disco mediante Gestione di sistema di SANtricity

(Argomento sull'appliance esistente - già combinato)
